#!/bin/bash

# 显示脚本执行过程
set -e

echo "开始安装 Docker..."

# 删除旧的 Docker 仓库配置（如果有）
echo "删除旧的 Docker 仓库配置..."
sudo rm -f /etc/yum.repos.d/docker-ce.repo

# 添加阿里云 Docker 镜像源
echo "添加阿里云 Docker 镜像源..."
sudo tee /etc/yum.repos.d/docker-ce.repo <<EOF
[docker-ce]
name=Docker CE Stable - \$basearch
baseurl=https://mirrors.aliyun.com/docker-ce/linux/centos/7/x86_64/stable/
enabled=1
gpgcheck=0
EOF

# 清理 YUM 缓存
echo "清理 YUM 缓存..."
sudo yum clean all

# 重新生成 YUM 缓存
echo "重新生成 YUM 缓存..."
sudo yum makecache

# 安装 Docker
echo "安装 Docker..."
sudo yum install -y docker-ce docker-ce-cli containerd.io

# 启动 Docker 服务并设置开机自启动
echo "启动 Docker 服务..."
sudo systemctl start docker
sudo systemctl enable docker

# 验证 Docker 是否安装成功
echo "验证 Docker 是否安装成功..."
sudo docker --version
sudo docker run hello-world

echo "Docker 安装完成!"


echo  "https://github.com/docker/compose/releases/download/v2.37.2/docker-compose-linux-x86_64"
